# Read the Docs configuration
# https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.12"
  commands:
    # Use uv for dependency installation (fast, deterministic)
    - pip install uv
    - uv venv $READTHEDOCS_VIRTUALENV_PATH
    - uv pip install --python $READTHEDOCS_VIRTUALENV_PATH/bin/python sphinx furo myst-parser sphinx-copybutton
    # Install project in mock-friendly mode (docs extras only)
    - uv pip install --python $READTHEDOCS_VIRTUALENV_PATH/bin/python -e ".[docs]"
    - $READTHEDOCS_VIRTUALENV_PATH/bin/python -m sphinx -b html docs/ $READTHEDOCS_OUTPUT/html

sphinx:
  configuration: docs/conf.py
  fail_on_warning: false
