# Read the Docs configuration
# https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.12"
  commands:
    # Install docs dependencies (sphinx, theme, extensions)
    - python -m pip install sphinx furo myst-parser sphinx-copybutton
    # Install project without heavy deps — autodoc_mock_imports handles the rest
    - python -m pip install --no-deps -e .
    # Build HTML docs
    - python -m sphinx -T -b html docs/ $READTHEDOCS_OUTPUT/html
